server:
  port: 9090
  servlet:
    context-path: /sntdractions

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8080/postgres
    username: postgres
    password: 11235813#
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Back-end project for Santander QuotesScreen - DEV WEEK